FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
ARG NODE_MAJOR=20

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl wget git unzip zip jq \
    build-essential python3 python3-pip python3-venv\
    openssh-client gnupg \
    libicu-dev \
    sqlite3 libsqlite3-dev \
    postgresql-client libpq-dev \
    && rm -rf /var/lib/apt/lists/*


RUN mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" \
    > /etc/apt/sources.list.d/nodesource.list \
 && apt-get update && apt-get install -y nodejs \
 && rm -rf /var/lib/apt/lists/*


RUN corepack enable

RUN wget -q https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb \
 && dpkg -i packages-microsoft-prod.deb \
 && rm packages-microsoft-prod.deb \
 && apt-get update \
 && apt-get install -y dotnet-sdk-8.0 \
 && rm -rf /var/lib/apt/lists/*

RUN npm install -g \
    vite \
    eslint \
    typescript

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install requests \
    psycopg2-binary \
    python-dotenv \
    fastapi \
    uvicorn \
    pytest

RUN useradd -ms /bin/bash dev
USER dev
ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /workspace

# Default ports:
# - 5173 Vite
# - 5000/5001 ASP.NET
# - 8081 Metro bundler (Expo)
# - 8000 fastAPI
EXPOSE 5173 5000 5001 8081 8000

CMD ["bash"]
